Name: 		findutils
Version: 	4.4.2
Release: 	3
Group: 		System Environment/Base
License:	GPLv3+
URL:		http://www.gnu.org/software/findutils	
Source: 	http://ftp.gnu.org/pub/gnu/findutils/findutils-%{version}.tar.gz
Patch0:         findutils-%{version}-aixconf.patch
BuildRoot: 	/var/tmp/%{name}-%{version}-%{release}-root
Prefix: %{_prefix}

Summary:	The GNU versions of find utilities (find and xargs)

Requires: /sbin/install-info, info, gettext

%description
The findutils package contains programs which will help you locate
files on your system.  The find utility searches through a hierarchy
of directories looking for files which match a certain set of criteria
(such as a filename pattern).  The xargs utility builds and executes
command lines from standard input arguments (usually lists of file
names generated by the find command).

You should install findutils because it includes tools that are very
useful for finding things on your system.

This package contains the find, xargs, updatedb, and locate tools.


%prep
%setup -q
%patch0 -p1 -b .aixconf


%build
# Use the default compiler for this platform - gcc otherwise
if [[ -z "$CC" ]]
then
    if test "X`type %{DEFCC} 2>/dev/null`" != 'X'; then
       export CC=%{DEFCC}
    else
       export CC=gcc
    fi
fi
if [[ "$CC" != "gcc" ]]
then
       export RPM_OPT_FLAGS=`echo $RPM_OPT_FLAGS | sed 's:-fsigned-char::'`
fi
export CFLAGS="$RPM_OPT_FLAGS -D_GNU_SOURCE"

./configure \
	--prefix=%{_prefix}		\
	--infodir=%{_prefix}/info	\
	--mandir=%{_prefix}/man

make 


%install
rm -rf $RPM_BUILD_ROOT
make prefix=${RPM_BUILD_ROOT}%{_prefix} \
     mandir=${RPM_BUILD_ROOT}%{_prefix}/man \
     infodir=${RPM_BUILD_ROOT}%{_prefix}/info \
     install

cd $RPM_BUILD_ROOT%{_prefix}

# Strip all of the executables
/usr/bin/strip bin/* 2>/dev/null || :


(   cd $RPM_BUILD_ROOT
    gzip -9fn .%{_prefix}/info/find.info*
    mkdir -p usr/linux/bin
    cd usr/linux/bin
    ln -sf ../../..%{prefix}/bin/* .
    cd -
    mkdir -p usr/bin
    cd usr/bin
    for f in locate updatedb oldfind
    do
      ln -sf ../..%{prefix}/bin/$f .
    done
)


%clean
rm -rf $RPM_BUILD_ROOT


%post
/sbin/install-info %{_prefix}/info/find.info.gz %{_prefix}/info/dir || :
/sbin/install-info %{_prefix}/info/find-maint.info %{_prefix}/info/dir || :
if [ ! -d  /usr/linux/libexec ]
then
   ln -sf %{_prefix}/libexec /usr/linux/libexec
fi

cat << EOF

If you run 'updatedb' in cron, make sure to run it as user 'nobody'
instead of 'root'.

EOF


%preun
if [ $1 = 0 ] ; then
	/sbin/install-info --delete %{_prefix}/info/find.info.gz %{_prefix}/info/dir || :
	/sbin/install-info --delete %{_prefix}/info/find-maint.info %{_prefix}/info/dir || :
fi


%files
%defattr(-, root, system)
%doc COPYING NEWS AUTHORS README THANKS TODO
/usr/bin/*
/usr/linux/bin/*
%{_prefix}/bin/find
%{_prefix}/bin/oldfind
%{_prefix}/bin/locate
%{_prefix}/bin/updatedb
%{_prefix}/bin/xargs
%{_prefix}/libexec/*
%{_prefix}/man/man1/find.1*
%{_prefix}/man/man1/locate.1*
%{_prefix}/man/man1/updatedb.1*
%{_prefix}/man/man1/xargs.1*
%{_prefix}/man/man5/locatedb.5*
%{_prefix}/info/find-maint*
%{_prefix}/info/find.info*
%{_prefix}/share/locale/*/LC_MESSAGES/findutils.mo


%changelog
* Wed Feb 01 2012 Gerard Visiedo <gerard.visiedo@bull.net> 4.4.2-3
- Initial port on Aix6.1


* Thu Sep 22 2011 Patricia Cugny <patricia.cugny@bull.net> 4.4.2-2
- rebuild for compatibility with new libiconv.a 1.13.1-2

* Wed Jun 1 2011 Gerard Visiedo <gerard.visiedo@bull.net>
- Update to 4.4.2

* Thu Jul 10 2003 David Clissold <cliss@austin.ibm.com>
- Switch to the IBM VAC compiler for performance and size.

* Fri Oct 27 2000 pkgmgr <pkgmgr@austin.ibm.com>
- Modify for AIX Freeware distribution

* Wed Feb 02 2000 Cristian Gafton <gafton@redhat.com>
- fix summary
- ma  pages are compressed

* Wed Jan 12 2000 Preston Brown <pbrown@redhat.com>
- new description.
