#! /bin/sh

if test $# != 0; then
  echo usage: update-gtk-immodules 1>&2
  exit 1
fi
 
umask 022

FILE=/etc/gtk-2.0/gtk.immodules

/opt/freeware/bin/gtk-query-immodules-2.0_64 > $FILE
/opt/freeware/bin/gtk-query-immodules-2.0    > $FILE

